/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /dev-server/src/assets/models/leon-user.glb --printwidth 120 
Author: Nx_cria (https://sketchfab.com/Gabriel777rr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/resident-evil-4-leon-50a47bd3f0fc43099c874ea354fb12ba
Title: Resident Evil 4 - Leon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/leon-user.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['0_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['0_leon_tex.tga']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['0_leon_tex.tga.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['0_pl0005.tga']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['0_pl0011.tga']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['0_pl0013.tga']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['10_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['10_pl0004.tga']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['11_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['11_pl0004.tga']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['12_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['12_pl0004.tga']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['13_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['13_pl0004.tga']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['14_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['15_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['16_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['17_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['18_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['19_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['1_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['1_leon_tex.tga']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['1_pl0004.tga']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['1_pl0005.tga']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['1_pl0012.tga']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['20_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['21_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['22_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['23_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['2_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['2_leon_tex.tga']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['2_pl0012.tga']} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['2_pl0012.tga.001']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['3_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['3_leon_tex.tga']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['3_pl0012.tga']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['3_pl0012.tga.001']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['4_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['4_leon_tex.tga']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['4_pl0004.tga']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['4_pl0012.tga']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['5_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['5_leon_tex.tga']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['5_pl0012.tga']} />
        <mesh geometry={nodes.Object_46.geometry} material={materials['5_pl0014.tga']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials['6_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_48.geometry} material={materials['6_leon_tex.tga']} />
        <mesh geometry={nodes.Object_49.geometry} material={materials['6_pl0012.tga']} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['6_pl0014.tga']} />
        <mesh geometry={nodes.Object_51.geometry} material={materials['7_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_52.geometry} material={materials['7_pl0012.tga']} />
        <mesh geometry={nodes.Object_53.geometry} material={materials['7_pl0014.tga']} />
        <mesh geometry={nodes.Object_54.geometry} material={materials['8_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_55.geometry} material={materials['8_pl0014.tga']} />
        <mesh geometry={nodes.Object_56.geometry} material={materials['9_leon_kami_n.tga']} />
        <mesh geometry={nodes.Object_57.geometry} material={materials['9_pl0004.tga']} />
        <mesh geometry={nodes.Object_58.geometry} material={materials['pl0005.tga']} />
      </group>
    </group>
  )
}

useGLTF.preload('/leon-user.glb')
