/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /dev-server/src/assets/models/zero-two-upload.glb --printwidth 120 
Author: M1LKA (https://sketchfab.com/milkami)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zero-two-motorcycle-77236bdca90447238171dc7422feb023
Title: Zero Two Motorcycle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/zero-two-upload.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/zero-two-upload.glb')
