export const VR_ACTION_ALIASES: Record<string, string> = {
  open_vr_world: 'open_vr',
  exit_vr_world: 'exit_vr',
  turn_left: 'turn_left_45',
  turn_right: 'turn_right_45',
  stop_movement: 'stop',
  run: 'run_forward',
  run_fast: 'sprint',
  jog: 'run_forward',
  leap: 'jump',
  fly_above_clouds: 'fly',
  create_vehicle: 'spawn_car',
  spawn_transport: 'spawn_car',
  spawn_vehicle: 'spawn_car',
  reset_camera: 'reset_view',
  zoom_reset: 'reset_view',
  zoom_max: 'zoom_5x',
  clear_weather: 'set_sunny',
  set_sunset: 'set_dusk',
  set_sunrise: 'set_dawn',
  list_commands: 'show_commands',
  what_can_do: 'show_commands',
  show_hud: 'open_controls_panel',
  hide_hud: 'minimize_all_panels',
  hide_controls: 'close_controls_panel',
  show_controls: 'open_controls_panel',
  show_wallet: 'open_wallet',
  toggle_mute: 'toggle_sound',
  toggle_fullscreen: 'fullscreen_toggle',
  go_to_f1: 'navigate_to_f1',
  take_me_to_f1: 'navigate_to_f1',
  f1_circuit: 'navigate_to_f1',
  get_in_f1_car: 'enter_f1_car',
  drive_f1: 'enter_f1_car',
  race: 'start_f1_race',
  start_race: 'start_f1_race',
  pit_stop: 'f1_pit_stop',
  check_standings: 'f1_standings',
  race_standings: 'f1_standings',
  lap_time: 'f1_lap_time',
  car_status: 'f1_car_status',
  tire_wear: 'f1_car_status',
  // Natural language F1 aliases
  formula_one: 'navigate_to_f1',
  race_track: 'navigate_to_f1',
  go_to_race: 'navigate_to_f1',
  take_me_to_race: 'navigate_to_f1',
  racing: 'navigate_to_f1',
  go_racing: 'navigate_to_f1',
  exit_car: 'exit_f1_car',
  get_out_car: 'exit_f1_car',
  get_out: 'exit_vehicle',
  check_lap: 'f1_lap_time',
  my_lap_time: 'f1_lap_time',
  // Metro/Train aliases
  board_metro: 'board_train',
  enter_train: 'board_train',
  get_on_train: 'board_train',
  leave_train: 'exit_train',
  get_off_train: 'exit_train',
  ride_metro: 'board_train',
  ride_train: 'board_train',
  take_metro: 'board_train',
  day_night: 'toggle_day_night',
  toggle_lighting: 'toggle_day_night',
  play_horn: 'force_train_horn',
  horn: 'force_train_horn',
  train_horn: 'force_train_horn',
  go_to_train_1: 'teleport_to_train_1',
  enter_train_1: 'teleport_to_train_1',
  download_report: 'download_vr_audit',
  export_pdf: 'download_vr_audit',
  vr_report: 'download_vr_audit',
  // Natural movement aliases
  walk: 'walk_forward',
  go_forward: 'walk_forward',
  move_forward: 'walk_forward',
  go_back: 'walk_backward',
  move_back: 'walk_backward',
  turn_around: 'turn_around_180',
  look_back: 'turn_around_180',
  // Interaction aliases
  sit_down: 'sit',
  stand_up: 'stand',
  get_up: 'stand',
  crouch_down: 'crouch',
  lay_down: 'lie_down',
  enter_car: 'enter_vehicle',
  get_in_car: 'enter_vehicle',
  leave_car: 'exit_vehicle',
  start_car: 'start_engine',
  stop_car: 'stop_engine',
  // Navigation aliases
  go_home: 'reset_view',
  take_me_home: 'reset_view',
  go_to_city: 'city_center_view',
  take_me_to_city: 'city_center_view',
  go_to_mountain: 'mountain_view',
  go_to_mountains: 'mountain_view',
  go_to_metro: 'navigate_to_metro',
  take_me_to_metro: 'navigate_to_metro',
  go_to_train: 'navigate_to_metro',
  // View aliases
  birds_eye: 'aerial_view',
  birds_eye_view: 'aerial_view',
  top_view: 'satellite_view',
  top_down: 'satellite_view',
  sky_view: 'satellite_view',
  panorama: 'mountain_summit_view',
  panoramic: 'mountain_summit_view',
  // Weather aliases
  make_it_rain: 'set_rain',
  make_it_snow: 'set_snow',
  clear_sky: 'set_sunny',
  sunny: 'set_sunny',
  nighttime: 'set_night',
  daytime: 'set_day',
};

export const VR_HANDLED_ACTIONS = new Set<string>([
  'open_vr', 'exit_vr', 'activate_voice', 'deactivate_voice',
  'walk_forward', 'run_forward', 'sprint', 'walk_backward', 'walk_left', 'walk_right', 'stop',
  'turn_left_45', 'turn_right_45', 'turn_around_180',
  'drive', 'drive_slow', 'drive_medium', 'drive_fast', 'accelerate', 'brake', 'park', 'spawn_car',
  'jump', 'jump_high', 'double_jump',
  'fly', 'fly_up', 'fly_down', 'hover', 'glide', 'land',
  'look_up', 'look_down', 'look_left', 'look_right', 'look_around', 'zoom_in', 'zoom_out',
  'zoom_5x', 'zoom_1x', 'reset_view',
  'first_person', 'first_person_view', 'third_person', 'third_person_view',
  'satellite_view', 'aerial_view', 'mountain_view', 'mountain_top_view', 'mountain_summit_view', 'city_center_view',
  'guide_vr_world',
  'fly_to_location', 'teleport_to',
  'search', 'find_users', 'find_malls', 'find_brands', 'find_products', 'find_store', 'show_avatars', 'show_buildings',
  'navigate_to_kfc', 'navigate_to_mcdonalds', 'navigate_to_starbucks', 'navigate_to_cafe',
  'navigate_to_hospital', 'navigate_to_hotel', 'navigate_to_school', 'navigate_to_church',
  'navigate_to_temple', 'navigate_to_metro', 'navigate_to_park', 'navigate_to_stadium',
  'navigate_to_fire_station', 'navigate_to_police', 'navigate_to_tower',
  'navigate_to_fashion', 'navigate_to_pet_shop', 'navigate_to_laundry',
  'navigate_to_vegetable_market', 'navigate_to_fruit_market',
  'set_day', 'set_night', 'set_dawn', 'set_dusk', 'set_sunny', 'set_rain', 'set_cloudy', 'set_snow', 'set_storm', 'set_fog',
  'set_season_winter', 'set_season_spring', 'set_season_summer', 'set_season_autumn',
  'sync_real_weather', 'sync_real_time', 'set_temperature', 'set_temp_preset',
  'toggle_sound', 'toggle_cyber_city',
  'fix_camera', 'fix_car', 'fix_house', 'fix_object', 'repair', 'restore',
  'enter_vehicle', 'exit_vehicle', 'start_engine', 'stop_engine', 'autopilot', 'manual_drive',
  'navigate_route', 'drive_to',
  'open_car_door', 'close_car_door', 'open_building_door', 'enter_building', 'open_door', 'close_door',
  'build_house', 'build_building', 'build_road', 'build_bridge', 'build_hospital', 'build_school', 'build_shop', 'build_park',
  'build_industrial', 'build_city', 'build_city_full', 'build_town', 'build_fire_station', 'build_police_station',
  'build_religious', 'build_gym', 'build_restaurant', 'build_cultural', 'build_stadium',
  'plant_tree', 'create_forest',
  'show_location', 'use_geolocation', 'show_map', 'teleport_real_place', 'recreate_place',
  'interact', 'pickup', 'drop', 'sit', 'stand', 'crouch', 'lie_down', 'interact_avatar', 'wave', 'dance',
  'bio_sync', 'restore_integrity', 'show_memories', 'select_engram', 'show_holowall', 'reset_world', 'show_zoe_orb',
  'show_help', 'show_commands', 'show_tutorial', 'fullscreen_toggle', 'show_bicameral', 'show_timeline',
  'open_voice_panel', 'close_voice_panel', 'toggle_voice_panel',
  'open_controls_panel', 'close_controls_panel', 'toggle_controls_panel',
  'open_wallet', 'close_wallet', 'toggle_wallet',
  'close_memory_panel', 'close_all_panels', 'minimize_all_panels', 'reset_panel_positions',
  // F1 Circuit
  'navigate_to_f1', 'enter_f1_car', 'exit_f1_car', 'start_f1_race', 'f1_pit_stop',
  'f1_standings', 'f1_lap_time', 'f1_car_status',
  // Metro / Train
  'board_train', 'exit_train', 'next_station', 'metro_status',
  'toggle_day_night', 'force_train_horn', 'teleport_to_train_1',
  'navigate_to_metro_entrance', 'download_vr_audit',
]);
