// ═══════════════════════════════════════════════════════════════════════════════
// ARTIFACT GENERATOR HOOK - Client-side artifact generation
// Part 5: The Visionary (Protocol Artifact)
// ═══════════════════════════════════════════════════════════════════════════════

import { useState, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { jsPDF } from 'jspdf';
import { detectArtifactIntent, ArtifactType, enhanceVisionPrompt, type VisionPromptContext } from './useArtifactDetector';
import { generateImage as generatePollinationsImage } from '@/services/pollinationsService';
import { toast } from 'sonner';

export interface GeneratedArtifact {
  id: string;
  type: ArtifactType;
  content: string;
  title: string;
  description?: string;
  timestamp: Date;
  isLoading?: boolean;
}

interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
}

interface ArtifactGenerationOptions {
  visionContext?: VisionPromptContext;
}

export function useArtifactGenerator() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentArtifact, setCurrentArtifact] = useState<GeneratedArtifact | null>(null);
  const [backgroundImage, setBackgroundImage] = useState<string | null>(null);

  // ═══════════════════════════════════════════════════════════════════════════
  // Generate Chronicle PDF
  // ═══════════════════════════════════════════════════════════════════════════
  const generateChronicle = useCallback((
    reportData: any,
    title: string,
    conversationHistory?: ConversationMessage[]
  ): Blob => {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Helper to add text with word wrap
    const addText = (text: string, fontSize: number, isBold = false) => {
      pdf.setFontSize(fontSize);
      pdf.setFont('helvetica', isBold ? 'bold' : 'normal');

      const lines = pdf.splitTextToSize(text, pageWidth - margin * 2);
      lines.forEach((line: string) => {
        if (y > pdf.internal.pageSize.getHeight() - 20) {
          pdf.addPage();
          y = 20;
        }
        pdf.text(line, margin, y);
        y += fontSize * 0.5;
      });
      y += 5;
    };

    // Title
    pdf.setFillColor(0, 0, 0);
    pdf.rect(0, 0, pageWidth, 40, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text(title || 'Conversation Chronicle', margin, 28);

    // Subtitle
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated by Zoe Infinity • ${new Date().toLocaleDateString()}`, margin, 36);

    y = 55;
    pdf.setTextColor(0, 0, 0);

    // Report content
    if (typeof reportData === 'object' && reportData !== null) {
      if (reportData.executive_summary || reportData.executiveSummary) {
        addText('EXECUTIVE SUMMARY', 14, true);
        addText(reportData.executive_summary || reportData.executiveSummary || '', 11);
        y += 5;
      }

      if (reportData.key_points || reportData.keyPoints) {
        addText('KEY POINTS', 14, true);
        const points = reportData.key_points || reportData.keyPoints || [];
        if (Array.isArray(points)) {
          points.forEach((point: string) => {
            addText(`• ${point}`, 11);
          });
        } else {
          addText(String(points), 11);
        }
        y += 5;
      }

      if (reportData.insights || reportData.insights_analysis) {
        addText('INSIGHTS & ANALYSIS', 14, true);
        addText(reportData.insights || reportData.insights_analysis || '', 11);
        y += 5;
      }

      if (reportData.recommendations) {
        addText('RECOMMENDATIONS', 14, true);
        const recs = reportData.recommendations;
        if (Array.isArray(recs)) {
          recs.forEach((rec: string) => {
            addText(`• ${rec}`, 11);
          });
        } else {
          addText(String(recs), 11);
        }
        y += 5;
      }

      if (reportData.conclusion) {
        addText('CONCLUSION', 14, true);
        addText(reportData.conclusion, 11);
      }

      if (reportData.content && !reportData.executive_summary) {
        addText(reportData.content, 11);
      }
    } else if (typeof reportData === 'string') {
      addText(reportData, 11);
    }

    // Conversation history section
    if (conversationHistory && conversationHistory.length > 0) {
      pdf.addPage();
      y = 20;

      addText('CONVERSATION TRANSCRIPT', 14, true);
      y += 5;

      conversationHistory.forEach((msg) => {
        const role = msg.role === 'user' ? 'You' : 'Zoe';
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(10);
        pdf.text(`${role}:`, margin, y);
        y += 5;

        pdf.setFont('helvetica', 'normal');
        const lines = pdf.splitTextToSize(msg.content, pageWidth - margin * 2 - 10);
        lines.forEach((line: string) => {
          if (y > pdf.internal.pageSize.getHeight() - 20) {
            pdf.addPage();
            y = 20;
          }
          pdf.text(line, margin + 5, y);
          y += 5;
        });
        y += 5;
      });
    }

    // Footer on each page
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(128, 128, 128);
      pdf.text(
        `Page ${i} of ${totalPages} • Zoe Infinity Chronicle`,
        pageWidth / 2,
        pdf.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }

    return pdf.output('blob');
  }, []);

  // Shared invoker (keeps all prompt + gateway wiring in one place)
  const invokeArtifact = useCallback(async (
    params: {
      type: Exclude<ArtifactType, 'none'>;
      prompt: string;
      subject?: string;
      conversationHistory?: ConversationMessage[];
      visionContext?: VisionPromptContext;
    }
  ): Promise<GeneratedArtifact | null> => {
    const { type, prompt, subject, conversationHistory, visionContext } = params;

    setIsGenerating(true);

    const loadingArtifact: GeneratedArtifact = {
      id: `artifact-${Date.now()}`,
      type,
      content: '',
      title: type === 'vision' ? 'Manifesting vision...'
        : type === 'chronicle' ? 'Compiling chronicle...'
        : 'Crafting worksheet...',
      timestamp: new Date(),
      isLoading: true,
    };

    setCurrentArtifact(loadingArtifact);

    try {
      if (type === 'vision') {
        const imagePrompt = enhanceVisionPrompt(prompt, visionContext);
        const imageResult = await generatePollinationsImage(imagePrompt, {
          width: 1024,
          height: 1024,
          timeoutMs: 20000,
        });

        console.log('[ArtifactGenerator] Vision generated via', imageResult.provider);

        const artifact: GeneratedArtifact = {
          id: `artifact-${Date.now()}`,
          type,
          content: imageResult.imageUrl,
          title: subject ? `${subject}` : 'Zoe Vision',
          description: `Generated via ${imageResult.provider}`,
          timestamp: new Date(),
          isLoading: false,
        };

        setBackgroundImage(imageResult.imageUrl);
        setTimeout(() => setBackgroundImage(null), 30000);
        setCurrentArtifact(artifact);
        return artifact;
      }

      const { data, error } = await supabase.functions.invoke('zoe-artifact-generator', {
        body: {
          type,
          prompt,
          subject,
          conversationHistory: conversationHistory?.slice(-10),
        },
      });

      if (error) {
        console.error('[ArtifactGenerator] Error:', error);
        toast.error('Failed to generate artifact');
        setCurrentArtifact(null);
        return null;
      }

      if (data?.error === 'RATE_LIMIT') {
        toast.error(data.message || 'Rate limit exceeded');
        setCurrentArtifact(null);
        return null;
      }

      if (data?.error === 'NO_CREDITS') {
        toast.error(data.message || 'Credits required');
        setCurrentArtifact(null);
        return null;
      }

      console.log('[ArtifactGenerator] Generated:', data.type);

      if (data.type === 'vision' && data.content) {
        setBackgroundImage(data.content);
        setTimeout(() => setBackgroundImage(null), 30000);
      }

      if (data.type === 'chronicle') {
        const pdfBlob = generateChronicle(data.content, data.title, conversationHistory);
        data.content = URL.createObjectURL(pdfBlob);
      }

      const artifact: GeneratedArtifact = {
        id: `artifact-${Date.now()}`,
        type: data.type,
        content: data.content,
        title: data.title,
        description: data.description,
        timestamp: new Date(),
        isLoading: false,
      };

      setCurrentArtifact(artifact);
      return artifact;
    } catch (err) {
      console.error('[ArtifactGenerator] Exception:', err);
      toast.error('Artifact generation failed');
      setCurrentArtifact(null);
      return null;
    } finally {
      setIsGenerating(false);
    }
  }, [generateChronicle]);

  // ═══════════════════════════════════════════════════════════════════════════
  // Generate artifact based on detected intent
  // ═══════════════════════════════════════════════════════════════════════════
  const generateArtifact = useCallback(async (
    message: string,
    conversationHistory?: ConversationMessage[],
    options?: ArtifactGenerationOptions
  ): Promise<GeneratedArtifact | null> => {
    const intent = detectArtifactIntent(message);
    
    if (intent.type === 'none') {
      return null;
    }

    // IMPORTANT: For vision requests, only send the *clean subject* to the image model.
    // Sending the full user sentence causes the model to literally draw text from the chat
    // (exactly the bug you saw with the "lazy" sentence appearing inside the image).
    const cleanedPrompt = intent.type === 'vision'
      ? intent.extractedSubject
      : message;

    return invokeArtifact({
      type: intent.type,
      prompt: cleanedPrompt,
      subject: intent.extractedSubject,
      conversationHistory,
      visionContext: intent.type === 'vision'
        ? {
            originalPrompt: message,
            ...options?.visionContext,
          }
        : undefined,
    });
  }, [invokeArtifact]);

  // Force a specific artifact type (used for auto-visions during conversation)
  const generateArtifactForced = useCallback(async (
    type: Exclude<ArtifactType, 'none'>,
    prompt: string,
    opts?: { subject?: string; conversationHistory?: ConversationMessage[]; visionContext?: VisionPromptContext }
  ) => {
    return invokeArtifact({
      type,
      prompt,
      subject: opts?.subject,
      conversationHistory: opts?.conversationHistory,
      visionContext: type === 'vision'
        ? {
            originalPrompt: prompt,
            ...opts?.visionContext,
          }
        : undefined,
    });
  }, [invokeArtifact]);

  // ═══════════════════════════════════════════════════════════════════════════
  // Download artifact
  // ═══════════════════════════════════════════════════════════════════════════
  const downloadArtifact = useCallback((artifact: GeneratedArtifact) => {
    if (!artifact.content) return;

    if (artifact.type === 'chronicle') {
      // Chronicle is already a blob URL
      const link = document.createElement('a');
      link.href = artifact.content;
      link.download = `${artifact.title.replace(/\s+/g, '_')}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      toast.success('Chronicle downloaded!');
    } else {
      // Vision/Education - download image
      const link = document.createElement('a');
      link.href = artifact.content;
      link.download = `${artifact.title.replace(/\s+/g, '_')}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      toast.success('Image downloaded!');
    }
  }, []);

  // ═══════════════════════════════════════════════════════════════════════════
  // Clear artifact
  // ═══════════════════════════════════════════════════════════════════════════
  const clearArtifact = useCallback(() => {
    setCurrentArtifact(null);
  }, []);

  const clearBackground = useCallback(() => {
    setBackgroundImage(null);
  }, []);

  return {
    isGenerating,
    currentArtifact,
    backgroundImage,
    generateArtifact,
    generateArtifactForced,
    downloadArtifact,
    clearArtifact,
    clearBackground,
    detectIntent: detectArtifactIntent,
  };
}
