import { useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/lib/auth';
import { useProactiveGreeting } from './useProactiveGreeting';

export const useDailyBriefing = () => {
  const { user } = useAuth();
  const { greetingMessage, hasGreeted, greetingData } = useProactiveGreeting();

  const checkAndDeliverBriefing = useCallback(async () => {
    if (!user) return;

    // Get user preferences
    const prefsStr = localStorage.getItem(`briefing_prefs_${user.id}`);
    const prefs = prefsStr ? JSON.parse(prefsStr) : {
      include_weather: true,
      include_events: true,
      include_trending_posts: true,
      include_news: false,
      enabled: true,
    };

    // Skip if disabled
    if (!prefs.enabled) {
      return;
    }

    // Check if already greeted today
    const lastGreetingDate = localStorage.getItem(`greeting_shown_${user.id}`);
    const today = new Date().toDateString();
    if (lastGreetingDate === today) {
      console.log('[useDailyBriefing] Already greeted today');
      return;
    }

    try {
      // Use the comprehensive greeting message generated by useProactiveGreeting
      if (greetingMessage && greetingData) {
        // Import and initialize voice system
        const { initializeZoeVoices, speakAsZoe } = await import('@/utils/zoeVoice');
        
        // Ensure voices are loaded
        await initializeZoeVoices();
        
        // Wait a moment for audio context to be ready
        await new Promise(resolve => setTimeout(resolve, 500));
        
        // Speak the greeting with Zoe's voice
        speakAsZoe(greetingMessage, {
          rate: 0.95,
          pitch: 1.1,
          volume: 1.0
        });

        console.log('[useDailyBriefing] Delivered comprehensive greeting:', greetingMessage.substring(0, 100));
        
        // Mark as greeted
        localStorage.setItem(`greeting_shown_${user.id}`, today);
      }
    } catch (error) {
      console.error('Error delivering daily briefing:', error);
    }
  }, [user, greetingMessage, greetingData]);

  // NOTE: Daily briefing auto-delivery disabled
  // EAP (Entity Activation Protocol) now handles the welcome voice message
  // This prevents duplicate/overlapping voice announcements on page load
  // Users can still manually trigger briefing via checkAndDeliverBriefing()

  return { checkAndDeliverBriefing };
};
