import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { BookOpen, Shield, FileText, Mail, MapPin, Scale } from "lucide-react";
import PageSeo from "@/components/seo/PageSeo";

const AboutPage = () => {
  const sections = [
    {
      icon: Scale,
      title: "Terms and Conditions",
      content: `Last Updated: December 2025

1. ACCEPTANCE OF TERMS
By accessing and using Universe of Life ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree, please discontinue use immediately.

2. RULES OF USE
Acceptable Use: Users must engage respectfully, provide accurate information, and comply with all applicable laws.
Prohibited Activities: Harassment, spam, unauthorized data scraping, malicious code distribution, impersonation, and intellectual property violations are strictly prohibited.

3. INTELLECTUAL PROPERTY RIGHTS
Platform Content: All content, including but not limited to text, graphics, logos, icons, audio, video, software, and AI-generated outputs (including Zoe AI Architect creations), is owned by Universe of Life or licensed to us.
User-Generated Content: You retain ownership of content you create, but grant us a worldwide, royalty-free license to use, modify, and distribute your content for platform operations and improvements.
AI-Generated Content: Content generated by Zoe AI Architect using your prompts is co-owned. You have full usage rights, while we retain rights for platform improvement and research purposes.

4. LIABILITY AND DISCLAIMERS
Service Availability: The Platform is provided "as-is" without warranties. We do not guarantee uninterrupted or error-free service.
Limitation of Liability: Universe of Life is not liable for indirect, incidental, or consequential damages arising from platform use.
AI Accuracy: Zoe AI Architect outputs are generated using advanced AI models but may contain inaccuracies. Users are responsible for verifying critical information.
Third-Party Services: We are not responsible for third-party integrations, external links, or services accessed through the Platform.

5. DATA AND PRIVACY
Your privacy is paramount. Please review our Privacy Policy for detailed information on data collection, processing, and protection. We employ enterprise-grade security, including AI-powered face verification and end-to-end encryption where applicable.

6. ACCOUNT SECURITY
You are responsible for maintaining account security, including password confidentiality and biometric authentication setup. Notify us immediately of any unauthorized access.

7. MODIFICATIONS TO SERVICE
We reserve the right to modify, suspend, or discontinue any aspect of the Platform at any time, with or without notice.

8. GOVERNING LAW
These Terms are governed by the laws of the jurisdiction in which Universe of Life operates. Disputes shall be resolved through binding arbitration.

9. CONTACT INFORMATION
For questions or concerns about these Terms, contact us at: support@universeoflife.app`
    },
    {
      icon: Shield,
      title: "Privacy Policy",
      content: `Last Updated: December 2025

INTRODUCTION
Universe of Life ("we," "us," "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our Platform.

INFORMATION WE COLLECT
Personal Information: Name, email address, phone number, profile photo, biometric data (face verification), location data (when enabled).
Usage Data: Activity logs, page views, feature interactions, voice command history, AI conversation data.
Technical Data: Device information, IP address, browser type, operating system, session tokens.
User-Generated Content: Posts, messages, comments, AI-generated creations, timeline entries.

HOW WE USE YOUR INFORMATION
Platform Operations: Account management, authentication, service delivery, personalization.
AI Enhancement: Training and improving Zoe AI Architect, voice recognition, recommendation systems.
Communication: Notifications, updates, security alerts, marketing (with consent).
Analytics: Usage patterns, performance monitoring, error detection, platform optimization.
Security: Fraud prevention, account protection, compliance with legal obligations.

DATA SHARING AND DISCLOSURE
We do NOT sell your personal information. We may share data with:
Service Providers: Cloud hosting (Supabase), AI services (Google Gemini), analytics tools.
Legal Requirements: When required by law, court order, or to protect rights and safety.
Business Transfers: In the event of merger, acquisition, or asset sale.

BIOMETRIC DATA (FACE VERIFICATION)
Face verification data is processed using advanced AI vision with 99.1% accuracy and advanced liveness detection.
Biometric templates are encrypted and stored securely, never shared with third parties without explicit consent.
You may disable face verification at any time through Security Settings.

DATA RETENTION
We retain your data as long as your account is active or as needed to provide services.
Deletion requests are honored within 30 days, except where retention is legally required.

YOUR RIGHTS
Access, correct, or delete your personal information.
Opt-out of marketing communications.
Request data portability (export your data).
Disable location tracking, voice features, or biometric authentication.

SECURITY MEASURES
Enterprise-grade encryption (AES-256), secure HTTPS transmission, row-level security policies, AI-powered anomaly detection, regular security audits.

CHILDREN'S PRIVACY
Our Platform is not intended for users under 13 years of age. We do not knowingly collect data from children.

INTERNATIONAL DATA TRANSFERS
Data may be transferred and stored in servers located outside your country. We ensure adequate safeguards for international transfers.

CHANGES TO PRIVACY POLICY
We may update this Privacy Policy periodically. Continued use after changes constitutes acceptance.

CONTACT US
Privacy inquiries: privacy@universeoflife.app`
    },
    {
      icon: FileText,
      title: "Refund & Cancellation Policy",
      content: `Last Updated: December 2025

SUBSCRIPTION SERVICES
Universe of Life offers premium subscription tiers with advanced features, increased AI usage limits, and priority support.

CANCELLATION POLICY
You may cancel your subscription at any time through Account Settings.
Cancellation takes effect at the end of the current billing period.
No partial refunds for unused subscription time.
After cancellation, your account reverts to the free tier, and premium features become unavailable.

REFUND POLICY
General Rule: All subscription fees are non-refundable, except where legally required.
Exceptions: Refunds may be issued in cases of:
  - Billing errors or duplicate charges
  - Service disruption lasting more than 72 consecutive hours
  - Unauthorized transactions (report within 14 days)

Refund Requests: Contact support@universeoflife.app with transaction details within 30 days of charge.

PAYMENT PROCESSING
Payments are processed securely through third-party providers.
Subscription auto-renews unless canceled before renewal date.
Price changes apply from the next billing cycle with 30 days' advance notice.

AI USAGE CREDITS
Unused AI credits (API calls, image generation) do not roll over and are non-refundable.
Credit limits reset monthly according to subscription tier.

FREE TRIAL
New users may be eligible for a free trial period (if offered).
Trials automatically convert to paid subscriptions unless canceled before trial expiration.

CONTACT FOR BILLING ISSUES
For billing inquiries or disputes: billing@universeoflife.app`
    },
    {
      icon: BookOpen,
      title: "About Universe of Life",
      content: `PLATFORM OVERVIEW
Universe of Life is a next-generation immersive platform powered by Zoe AI Architect, designed to unite creativity, knowledge, and human connection across the cosmos of human interests and domains.

OUR MISSION
To empower humanity with adaptive AI intelligence that learns, creates, and collaborates—transforming how we explore history, envision futures, and build meaningful connections.

KEY FEATURES
• Zoe AI Architect: Agentic AI agent capable of creating and building across 50+ human interests and domains.
• Universal Agentic Timeline: Immersive visualization of cosmic and human history from the Big Bang to future predictions.
• Huddle: Real-time global user map with advanced filtering (location, interests, status, friends).
• Voice Intelligence: Natural language commands, proactive greetings, personalized briefings.
• AI Face Verification: 99.1% accuracy biometric authentication with 3D facial mapping and liveness detection.
• Private Timelines: Share moments with selected groups through blue-heart-marked posts.
• Creative Workflows: Drafts system, production plans with EPI (Estimated Production Index), shareable to global/friends feeds.

TECHNOLOGY STACK
Frontend: React, TypeScript, Tailwind CSS, Framer Motion
Backend: Cloud Infrastructure, PostgreSQL, Row-Level Security
AI: Advanced AI Models for Intelligence and Vision
Voice: Browser Text-to-Speech, Wake Word Detection, Natural Language Processing
Mobile: Capacitor for iOS/Android builds with native OS integrations

ENTERPRISE READINESS
• Multi-region scalable architecture
• CI/CD pipelines for rapid deployment
• GDPR, CCPA, SOC 2 compliance pathways
• iOS App Store and Android Play Store guidelines adherence

VISION
Universe of Life is not just a platform—it's a creative and operational partner from the future, designed to adapt, learn, and grow with humanity's expanding knowledge and ambitions.

COMPANY INFORMATION
Platform: Universe of Life
Founded: 2024
Technology Partner: Powered by Advanced AI Technology
Version: V1.00 (December 2025)

CONTACT
General Inquiries: hello@universeoflife.app
Support: support@universeoflife.app
Security: security@universeoflife.app
Enterprise: enterprise@universeoflife.app`
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background/95 to-primary/5 pb-20">
      <PageSeo
        title="About Universe of Life — MMora"
        description="Learn about Universe of Life, the team behind MMora and Zoe, our mission, contact details and platform principles."
      />

      <div className="container mx-auto px-4 pt-8 max-w-5xl">
        {/* Header */}
        <div className="text-center mb-12 space-y-4">
          <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent animate-gradient">
            About Universe of Life
          </h1>
          <p className="text-muted-foreground text-lg">
            Legal Information & Platform Documentation
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((section, index) => {
            const Icon = section.icon;
            return (
              <Card
                key={index}
                className="backdrop-blur-xl bg-card/40 border-border/50 hover:border-primary/30 transition-all duration-300 hover:shadow-xl hover:shadow-primary/10"
              >
                <div className="p-6 md:p-8 space-y-4">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-3 rounded-xl bg-primary/10 backdrop-blur-sm">
                      <Icon className="h-6 w-6 text-primary" />
                    </div>
                    <h2 className="text-2xl font-bold text-foreground">
                      {section.title}
                    </h2>
                  </div>
                  <Separator className="bg-border/30" />
                  <div className="prose prose-invert max-w-none">
                    <pre className="whitespace-pre-wrap text-sm text-muted-foreground font-sans leading-relaxed">
                      {section.content}
                    </pre>
                  </div>
                </div>
              </Card>
            );
          })}
        </div>

        {/* Contact Section */}
        <Card className="mt-12 backdrop-blur-xl bg-card/40 border-border/50">
          <div className="p-6 md:p-8">
            <div className="flex items-center gap-3 mb-6">
              <Mail className="h-6 w-6 text-primary" />
              <h2 className="text-2xl font-bold">Contact Information</h2>
            </div>
            <div className="grid md:grid-cols-2 gap-6 text-sm">
              <div className="space-y-2">
                <p className="text-muted-foreground">
                  <strong className="text-foreground">General Inquiries:</strong> hello@universeoflife.app
                </p>
                <p className="text-muted-foreground">
                  <strong className="text-foreground">Support:</strong> support@universeoflife.app
                </p>
              </div>
              <div className="space-y-2">
                <p className="text-muted-foreground">
                  <strong className="text-foreground">Security:</strong> security@universeoflife.app
                </p>
                <p className="text-muted-foreground">
                  <strong className="text-foreground">Enterprise:</strong> enterprise@universeoflife.app
                </p>
              </div>
            </div>
          </div>
        </Card>

        {/* Copyright */}
        <div className="text-center mt-12 text-sm text-muted-foreground">
          <p>© 2023-2026 Universe of Life. All Rights Reserved.</p>
          <p className="mt-2">Powered by Zoe AI Architect</p>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
