import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { X, Trash2, Sparkles, Download, Share2 } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';

interface Draft {
  id: string;
  type: 'text' | 'image' | 'zoe-architect';
  content: string;
  caption?: string;
  timestamp: number;
  zoeData?: {
    themeTitle: string;
    narrative: string;
    visualDesign: string;
    audioDesign?: string;
    executionNotes?: string;
    environmentContext: string;
    sourcingQueries?: string[];
    estimatedProductionIndex?: {
      tier1Core: string;
      tier2Premier: string;
      authorizeProcurement: string;
    };
    imageUrl?: string;
    userInput: string;
  };
}

interface DraftsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const DraftsModal: React.FC<DraftsModalProps> = ({ isOpen, onClose }) => {
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [selectedDraft, setSelectedDraft] = useState<Draft | null>(null);

  useEffect(() => {
    if (isOpen) {
      loadDrafts();
    }
  }, [isOpen]);

  const loadDrafts = () => {
    const stored = localStorage.getItem('webdrop_drafts');
    if (stored) {
      setDrafts(JSON.parse(stored));
    }
  };

  const saveDrafts = (updatedDrafts: Draft[]) => {
    localStorage.setItem('webdrop_drafts', JSON.stringify(updatedDrafts));
    setDrafts(updatedDrafts);
  };

  const handleDeleteDraft = (draftId: string) => {
    const updated = drafts.filter(d => d.id !== draftId);
    saveDrafts(updated);
    if (selectedDraft?.id === draftId) {
      setSelectedDraft(null);
    }
    toast.success('Draft deleted');
  };

  const handleDownloadZoeArchitect = (draft: Draft) => {
    if (!draft.zoeData) return;

    const documentContent = `
═══════════════════════════════════════════════════════════════
                    ZOE ARCHITECT PRODUCTION PLAN
═══════════════════════════════════════════════════════════════

THEME TITLE:
${draft.zoeData.themeTitle}

NARRATIVE ARC:
${draft.zoeData.narrative}

═══════════════════════════════════════════════════════════════
                          VISUAL DESIGN
═══════════════════════════════════════════════════════════════

${draft.zoeData.visualDesign}

═══════════════════════════════════════════════════════════════
                          AUDIO DESIGN
═══════════════════════════════════════════════════════════════

${draft.zoeData.audioDesign || 'Not available'}

═══════════════════════════════════════════════════════════════
                    TECHNICAL SPECIFICATIONS
═══════════════════════════════════════════════════════════════

${draft.zoeData.environmentContext}

═══════════════════════════════════════════════════════════════
                  SOURCING & BUDGET VALIDATION
═══════════════════════════════════════════════════════════════

${draft.zoeData.sourcingQueries?.map((q, idx) => `${idx + 1}. ${q}`).join('\n') || 'Not available'}

${draft.zoeData.estimatedProductionIndex ? `
═══════════════════════════════════════════════════════════════
              ESTIMATED PRODUCTION INDEX (EPI)
═══════════════════════════════════════════════════════════════

TIER 1 (CORE):
${draft.zoeData.estimatedProductionIndex.tier1Core}

TIER 2 (PREMIER):
${draft.zoeData.estimatedProductionIndex.tier2Premier}

${draft.zoeData.estimatedProductionIndex.authorizeProcurement}
` : ''}
═══════════════════════════════════════════════════════════════
                   14-SECOND VIDEO CREATOR PROMPTS
═══════════════════════════════════════════════════════════════

PRIMARY VISUAL PROMPT:
${draft.zoeData.visualDesign.split('\n').slice(0, 3).join(' ')}

AUDIO PROMPT:
${draft.zoeData.audioDesign?.split('\n')[0] || 'Music Creation Function: Coming Soon'}

ENVIRONMENT SETTING:
${draft.zoeData.environmentContext.split('\n')[0]}

═══════════════════════════════════════════════════════════════
Generated by Zoe Architect - AI Creative Production Designer
Date: ${new Date(draft.timestamp).toLocaleString()}
═══════════════════════════════════════════════════════════════
    `.trim();

    const blob = new Blob([documentContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `zoe-architect-${draft.zoeData.themeTitle.toLowerCase().replace(/\s+/g, '-')}-${draft.timestamp}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success('Production plan downloaded!', {
      description: 'Includes video creator prompts',
      icon: '📥'
    });
  };

  const handleShareZoeArchitect = async (draft: Draft, visibility: 'global' | 'personal', privateTimelineId?: string) => {
    if (!draft.zoeData) return;

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Create a formatted post content
      const postContent = `🎨 Zoe Architect Creation: ${draft.zoeData.themeTitle}\n\n${draft.zoeData.narrative}\n\n#ZoeArchitect #CreativeProduction`;

      const postData = {
        user_id: user.id,
        content: postContent,
        media_url: draft.zoeData.imageUrl || null,
        media_type: draft.zoeData.imageUrl ? 'image' : null,
        visibility: visibility,
        private_timeline_id: privateTimelineId || null
      };

      const { error } = await supabase.from('posts').insert(postData);
      if (error) throw error;

      const destination = privateTimelineId ? 'private timeline' : visibility === 'personal' ? 'friends feed' : 'global feed';
      toast.success(`Shared to ${destination}!`);
      
      setSelectedDraft(null);
    } catch (error) {
      console.error('Share error:', error);
      toast.error('Failed to share production');
    }
  };

  const handlePostDraft = async (visibility: 'global' | 'personal') => {
    if (!selectedDraft) return;

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const postData = selectedDraft.type === 'image' 
        ? {
            user_id: user.id,
            content: selectedDraft.caption || null,
            media_url: selectedDraft.content,
            media_type: 'image',
            visibility: visibility
          }
        : {
            user_id: user.id,
            content: selectedDraft.content,
            media_url: null,
            media_type: null,
            visibility: visibility
          };

      const { error } = await supabase.from('posts').insert(postData);
      if (error) throw error;

      toast.success(`Posted to ${visibility === 'personal' ? 'friends' : 'global'} feed!`);
      
      // Remove draft after posting
      handleDeleteDraft(selectedDraft.id);
      setSelectedDraft(null);
    } catch (error) {
      console.error('Post error:', error);
      toast.error('Failed to post');
    }
  };

  if (selectedDraft) {
    return (
      <Dialog open={isOpen} onOpenChange={onClose}>
        <DialogContent className={`${selectedDraft.type === 'zoe-architect' ? 'max-w-7xl' : 'max-w-2xl'} bg-black/95 backdrop-blur-xl border border-white/20 text-white`}>
          <DialogHeader>
            <div className="flex items-center justify-between">
              <DialogTitle className="text-white">
                {selectedDraft.type === 'zoe-architect' ? 'Zoe Architect Creation' : 'Draft Preview'}
              </DialogTitle>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => handleDeleteDraft(selectedDraft.id)}
                className="text-red-400 hover:text-red-300 hover:bg-red-400/10"
              >
                <Trash2 className="w-5 h-5" />
              </Button>
            </div>
          </DialogHeader>

          <div className="space-y-4 max-h-[70vh] overflow-y-auto">
            {selectedDraft.type === 'zoe-architect' && selectedDraft.zoeData ? (
              <div className="grid lg:grid-cols-2 gap-6">
                {/* Text Content */}
                <div className="space-y-4">
                  {/* Original Input */}
                  <div className="p-4 rounded-xl bg-white/5 border border-white/10">
                    <p className="text-xs text-white/50 uppercase tracking-wider mb-2">Original Prompt</p>
                    <p className="text-white/90 italic">"{selectedDraft.zoeData.userInput}"</p>
                  </div>

                  {/* Theme Title */}
                  <div className="p-4 rounded-xl bg-gradient-to-br from-primary/20 via-background/40 to-accent/20 border border-primary/30">
                    <h2 className="text-2xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent mb-2">
                      {selectedDraft.zoeData.themeTitle}
                    </h2>
                    <p className="text-white/80 italic">
                      {selectedDraft.zoeData.narrative}
                    </p>
                  </div>

                  {/* Visual Design */}
                  <div className="p-4 rounded-xl bg-white/5 border border-white/10">
                    <h3 className="text-sm font-semibold text-white/70 mb-2 flex items-center gap-2">
                      <Sparkles className="w-4 h-4 text-primary" />
                      Visual Design
                    </h3>
                    <p className="text-white/90 text-sm leading-relaxed whitespace-pre-line">
                      {selectedDraft.zoeData.visualDesign}
                    </p>
                  </div>

                  {/* Audio Design */}
                  {selectedDraft.zoeData.audioDesign && (
                    <div className="p-4 rounded-xl bg-white/5 border border-white/10">
                      <h3 className="text-sm font-semibold text-white/70 mb-2 flex items-center gap-2">
                        <Sparkles className="w-4 h-4 text-primary" />
                        Audio Design
                      </h3>
                      <p className="text-white/90 text-sm leading-relaxed whitespace-pre-line">
                        {selectedDraft.zoeData.audioDesign}
                      </p>
                    </div>
                  )}

                  {/* Technical Specs & Sourcing */}
                  <div className="space-y-4">
                    <div className="p-3 rounded-xl bg-white/5 border border-white/10">
                      <h4 className="text-xs font-semibold text-white/50 mb-2">Technical Specs</h4>
                      <p className="text-xs text-white/80">{selectedDraft.zoeData.environmentContext}</p>
                    </div>
                    
                    {selectedDraft.zoeData.sourcingQueries && Array.isArray(selectedDraft.zoeData.sourcingQueries) && selectedDraft.zoeData.sourcingQueries.length > 0 && (
                      <div className="p-3 rounded-xl bg-gradient-to-br from-primary/10 to-accent/10 border border-primary/20">
                        <h4 className="text-xs font-semibold text-primary mb-2">Sourcing & Budget Validation</h4>
                        <ul className="space-y-2">
                          {selectedDraft.zoeData.sourcingQueries.map((query: string, idx: number) => (
                            <li key={idx} className="text-xs text-white/80 flex items-start gap-2">
                              <span className="text-primary font-bold">{idx + 1}.</span>
                              <span>{query}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                </div>

                {/* Generated Image */}
                <div className="relative">
                  {selectedDraft.zoeData.imageUrl ? (
                    <div className="relative rounded-xl overflow-hidden shadow-2xl border border-primary/20">
                      <img 
                        src={selectedDraft.zoeData.imageUrl} 
                        alt={selectedDraft.zoeData.themeTitle}
                        className="w-full h-auto object-cover"
                      />
                      <div className="absolute bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-black/80 to-transparent">
                        <p className="text-xs text-white/70 uppercase tracking-wider">
                          Visual Concept by Zoe
                        </p>
                      </div>
                    </div>
                  ) : (
                    <div className="rounded-xl border-2 border-dashed border-white/20 bg-white/5 p-12 text-center">
                      <Sparkles className="w-12 h-12 text-white/30 mx-auto mb-4" />
                      <p className="text-white/50">Visual concept unavailable</p>
                    </div>
                  )}
                </div>
              </div>
            ) : selectedDraft.type === 'image' ? (
              <>
                <img
                  src={selectedDraft.content}
                  alt="Draft"
                  className="w-full rounded-lg"
                />
                {selectedDraft.caption && (
                  <p className="text-white/90">{selectedDraft.caption}</p>
                )}
              </>
            ) : (
              <div className="bg-white/5 border border-white/10 rounded-lg p-6">
                <p className="text-white whitespace-pre-wrap">{selectedDraft.content}</p>
              </div>
            )}
          </div>

          <div className="flex gap-3 pt-4">
            <Button
              onClick={() => setSelectedDraft(null)}
              variant="outline"
              className="flex-1 bg-white/10 text-white border-white/20 hover:bg-white/20"
            >
              Back to Drafts
            </Button>
            {selectedDraft.type === 'zoe-architect' ? (
              <>
                <Button
                  onClick={() => handleDownloadZoeArchitect(selectedDraft)}
                  className="flex-1 bg-white/10 backdrop-blur-xl text-white hover:bg-white/20 border border-white/30"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download
                </Button>
                <Button
                  onClick={() => handleShareZoeArchitect(selectedDraft, 'global')}
                  className="flex-1 bg-white/20 text-white hover:bg-white/30 border border-white/30"
                >
                  <Share2 className="w-4 h-4 mr-2" />
                  Share to Global
                </Button>
                <Button
                  onClick={() => handleShareZoeArchitect(selectedDraft, 'personal')}
                  className="flex-1 bg-white/20 text-white hover:bg-white/30 border border-white/30"
                >
                  <Share2 className="w-4 h-4 mr-2" />
                  Share to Friends
                </Button>
              </>
            ) : (
              <>
                <Button
                  onClick={() => handlePostDraft('global')}
                  className="flex-1 bg-white/20 text-white hover:bg-white/30 border border-white/30"
                >
                  Post to Global
                </Button>
                <Button
                  onClick={() => handlePostDraft('personal')}
                  className="flex-1 bg-white/20 text-white hover:bg-white/30 border border-white/30"
                >
                  Post to Friends
                </Button>
              </>
            )}
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl bg-black/95 backdrop-blur-xl border border-white/20 text-white">
        <DialogHeader>
          <DialogTitle className="text-white">My Drafts</DialogTitle>
        </DialogHeader>

        {drafts.length === 0 ? (
          <div className="py-12 text-center text-white/50">
            <p>No drafts saved yet</p>
          </div>
        ) : (
          <div className="grid grid-cols-3 gap-4 max-h-[60vh] overflow-y-auto">
            {drafts.map((draft) => (
              <button
                key={draft.id}
                onClick={() => setSelectedDraft(draft)}
                className="relative aspect-square bg-white/5 rounded-lg overflow-hidden border border-white/10 hover:border-white/30 transition-all group"
              >
                {draft.type === 'zoe-architect' && draft.zoeData ? (
                  <div className="relative w-full h-full">
                    {draft.zoeData.imageUrl ? (
                      <img
                        src={draft.zoeData.imageUrl}
                        alt={draft.zoeData.themeTitle}
                        className="w-full h-full object-cover"
                      />
                    ) : (
                      <div className="w-full h-full bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center">
                        <Sparkles className="w-12 h-12 text-white/50" />
                      </div>
                    )}
                    <div className="absolute bottom-0 left-0 right-0 p-3 bg-gradient-to-t from-black/90 to-transparent">
                      <p className="text-white text-xs font-semibold line-clamp-2">
                        {draft.zoeData.themeTitle}
                      </p>
                      <p className="text-white/60 text-[10px] mt-1">Zoe Architect</p>
                    </div>
                  </div>
                ) : draft.type === 'image' ? (
                  <img
                    src={draft.content}
                    alt="Draft"
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <div className="w-full h-full p-4 flex items-start">
                    <p className="text-white/90 text-sm text-left line-clamp-6">
                      {draft.content}
                    </p>
                  </div>
                )}
                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/40 transition-all" />
              </button>
            ))}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
};

export default DraftsModal;