/**
 * Canonical route registry generator.
 *
 * Parses every <Route path="..."> in src/App.tsx and emits
 * src/config/routeRegistry.generated.ts — the single source of truth consumed
 * by the Unified Search Dock and by Zoe's platform-state injection, so no menu
 * can exist in the app without Zoe knowing about it.
 *
 * Run: bun scripts/generate-route-registry.ts
 * Drift is enforced by src/test/routeRegistry.test.ts.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const APP = resolve(process.cwd(), 'src/App.tsx');
const OUT = resolve(process.cwd(), 'src/config/routeRegistry.generated.ts');

const TITLE_OVERRIDES: Record<string, string> = {
  '/': 'Root',
  '/home': 'Home feed',
  '/dhf-dashboard': 'DHF dashboard',
  '/zoe-ai': 'Zoe AI',
  '/mmora': "M'Mora",
  '/asi-test': 'ASI test',
  '/vr-audit': 'VR audit',
  '/admin/dhf-generation': 'Admin · DHF generation',
};

function labelFor(path: string): string {
  if (TITLE_OVERRIDES[path]) return TITLE_OVERRIDES[path];
  const segments = path.split('/').filter(Boolean).filter((s) => !s.startsWith(':'));
  if (!segments.length) return 'Root';
  const pretty = segments
    .map((s) => s.replace(/-/g, ' '))
    .join(' · ')
    .replace(/\bzoe\b/gi, 'Zoe')
    .replace(/\bdhf\b/gi, 'DHF')
    .replace(/\bvr\b/gi, 'VR');
  return pretty.charAt(0).toUpperCase() + pretty.slice(1);
}

export function extractRoutes(source: string): string[] {
  const found = new Set<string>();
  for (const match of source.matchAll(/path=["']([^"']+)["']/g)) {
    const path = match[1];
    if (path === '*') continue;
    found.add(path);
  }
  return [...found].sort();
}

export function buildRegistrySource(paths: string[]): string {
  const rows = paths
    .map((path) => {
      const dynamic = path.includes(':');
      return `  { path: ${JSON.stringify(path)}, label: ${JSON.stringify(labelFor(path))}, dynamic: ${dynamic} },`;
    })
    .join('\n');

  return `/**
 * AUTO-GENERATED by scripts/generate-route-registry.ts — do not edit by hand.
 * Canonical list of every route mounted in src/App.tsx.
 */
export interface CanonicalRoute {
  path: string;
  label: string;
  /** True for parameterised routes such as /profile/:userId. */
  dynamic: boolean;
}

export const CANONICAL_ROUTES: CanonicalRoute[] = [
${rows}
];
`;
}

export function writeRegistry(): number {
  const source = readFileSync(APP, 'utf8');
  const paths = extractRoutes(source);
  writeFileSync(OUT, buildRegistrySource(paths));
  return paths.length;
}

// Only write when executed directly (never on import from tests).
const invokedDirectly = process.argv[1]?.includes('generate-route-registry');
if (invokedDirectly) {
  console.log(`[route-registry] wrote ${writeRegistry()} routes to ${OUT}`);
}
